#pragma config(Motor,  port1,           right,         tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           left,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           rightArm1,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           rightArm2,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           leftArm1,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           leftArm2,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           rightClaw,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           leftClaw,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           left2,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          right2,        tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


void driveControl
task main()
{
	while(1 == 1)
	{
		//Driving Motor Control
		motor[right]= vexRT[Ch3];
		motor[left] = vexRT[Ch2];
		motor[right2]= -vexRT[Ch3];
		motor[left2] = -vexRT[Ch2];

		if(vexRT[Btn6D] == 1)
		{
			motor[rightArm1] = 127;
			motor[rightArm2] = 127;
			motor[leftArm1] = 127;
			motor[leftArm2] = 127;
		}
		else if(vexRT[Btn6U] == 1)  	//Else, if button 5D is pressed...
		{
			motor[rightArm1] = -127;
			motor[rightArm2] = -127;
			motor[leftArm1] = -127;
			motor[leftArm2] = -127;   	//...lower the arm.
		}
		else                      		//Else (neither button is pressed)...
		{
			motor[rightArm1] = 0;
			motor[rightArm2] = 0;
			motor[leftArm1] = 0;
			motor[leftArm2] = 0;     	//...stop the arm.
		}

		if(vexRT[Btn8R] == 1)       	//If button 5U is pressed...
		{
			motor[rightClaw] = 50;
			motor[leftClaw] = 50;   	//...raise the arm.
		}
		else if(vexRT[Btn8L] == 1)  	//Else, if button 5D is pressed...
		{
			motor[rightClaw] = -50;
			motor[leftClaw] = -50;  	//...lower the arm.
		}
		else                      		//Else (neither button is pressed)...
		{
			//Else (neither button is pressed)...
			motor[rightClaw] = 0;
			motor[leftClaw] = 0;   	//...stop the arm.
		}}}
