#pragma config(Sensor, in1,    rightPot,       sensorPotentiometer)
#pragma config(Sensor, in2,    leftPot,        sensorPotentiometer)
#pragma config(Motor,  port1,           right,         tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           left,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           rightArm1,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rightArm2,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           leftArm1,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           leftArm2,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           rightClaw,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           leftClaw,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           left2,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          right2,        tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

bool lockPincer = false;
int clawAdditionalPower = 0;

void driveControl()
{
	motor[right]= vexRT[Ch3];
	motor[left] = vexRT[Ch2];
	motor[right2]= -vexRT[Ch3];
	motor[left2] = -vexRT[Ch2];
}

//Allows the claw to move from the open position to the close position manually
void basicClaw()
{
	int openRight = 2100;
	int openLeft = 2000;

	int closeRight = 3500;
	int closeLeft = 3400;

	int maxSpeed = 75;

	if(vexRT[Btn5U])
	{
		if(SensorValue[rightPot] < closeRight)
		{
			motor[rightClaw] = maxSpeed;
		}
		else
		{
			motor[rightClaw] = 0;
		}

		if(SensorValue[leftPot] < closeLeft)
		{
			motor[leftClaw] = -maxSpeed;
		}
		else
		{
			motor[leftClaw] = 0;
		}
	}
	else if(vexRT[Btn5D])
	{
		if(SensorValue[rightPot] > openRight)
		{
			motor[rightClaw] = -maxSpeed;
		}
		else
		{
			motor[rightClaw] = 0;
		}

		if(SensorValue[leftPot] > openLeft)
		{
			motor[leftClaw] = maxSpeed;
		}
		else
		{
			motor[leftClaw] = 0;
		}
	}
	else
	{
		motor[rightClaw] = clawAdditionalPower;
		motor[leftClaw] = -clawAdditionalPower;
	}
}

bool lockClawButtonPressed = false;
void lockClaw()
{
	if(vexRT[Btn7D] && !lockClawButtonPressed)
	{
		lockPincer = !lockPincer;
		lockClawButtonPressed = true;
	}
	else if(!vexRT[Btn7D])
	{
		lockClawButtonPressed = false;
	}

	if(lockPincer)
	{
		if(SensorValue[rightPot] < 4000)
		{
			clawAdditionalPower = 50;
		}
		else
		{
			clawAdditionalPower = 0;
		}
	}
	else
	{
		clawAdditionalPower = 0;
	}
}


void childsPlay()
{
	driveControl();
	basicClaw();
	wait1Msec(20);
}

void moveArmBasic()
{
	if(vexRT[Btn6D] == 1)
	{
		motor[rightArm1] = 127;
		motor[rightArm2] = 127;
		motor[leftArm1] = 127;
		motor[leftArm2] = 127;
	}
	else if(vexRT[Btn6U] == 1)  	//Else, if button 5D is pressed...
	{
		motor[rightArm1] = -127;
		motor[rightArm2] = -127;
		motor[leftArm1] = -127;
		motor[leftArm2] = -127;   	//...lower the arm.
	}
	else                      		//Else (neither button is pressed)...
	{
		motor[rightArm1] = 0;
		motor[rightArm2] = 0;
		motor[leftArm1] = 0;
		motor[leftArm2] = 0;     	//...stop the arm.
	}
}

void fullControl()
{
	driveControl();
	basicClaw();
	lockClaw();
	moveArmBasic();
	wait1Msec(20);
}

task main()
{
	while(1 == 1)
	{
		fullControl();
	}
}
