#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    rightPot,       sensorPotentiometer)
#pragma config(Sensor, in2,    leftPot,        sensorPotentiometer)
#pragma config(Sensor, in3,    autoControl,    sensorNone)
#pragma config(Sensor, in4,    accelRight,     sensorAccelerometer)
#pragma config(Sensor, in5,    accelLeft,      sensorAccelerometer)
#pragma config(Sensor, dgtl1,  autoSensor,     sensorTouch)
#pragma config(Sensor, dgtl2,  bottomLimit,    sensorNone)
#pragma config(Sensor, dgtl3,  autoSensor,     sensorNone)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_4,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           frontLeft,     tmotorVex393_HBridge, openLoop, encoderPort, I2C_2)
#pragma config(Motor,  port2,           frontRight,    tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_3)
#pragma config(Motor,  port9,           backRight,     tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_4)
#pragma config(Motor,  port10,          backLeft,      tmotorVex393_HBridge, openLoop, encoderPort, I2C_1)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*--------------------------------General Variables ------------------------------*/
float WHEEL_BASE = 30;
float LEFT_CLICKS_PER_INCH = 27;
float RIGHT_CLICKS_PER_INCH = 27;
float traveled = 0;								//distanced traveled from set point

/*--------------------------------------------------------------------------------*/

/*--------------------------------Odometry ---------------------------------------*/
//Variables
float thetaOdo = PI/2;                    /* bot heading */
float xOdo=0;                    /* bot X position in inches */
float yOdo=0;                    /* bot Y position in inches */

//Odomery
void odometry()
{
	nMotorEncoder[backRight] = 0;
	nMotorEncoder[backLeft] = 0;
	int lsamp = 0;
	int rsamp = 0;
	int L_ticks = 0;
	int R_ticks = 0;
	int last_left = 0;
	int last_right = 0;
	float x1,y1;
	float left_inches, right_inches, inches;
	lsamp = nMotorEncoder[backRight];
	rsamp = nMotorEncoder[backLeft];

	//Change in encoder values
	L_ticks = lsamp - last_left;
	R_ticks = rsamp - last_right;

	//Update past encodervalues for next pass
	last_left = lsamp;
	last_right = rsamp;

	//Calculate the distance each wheel has travled
	left_inches = (float)L_ticks/LEFT_CLICKS_PER_INCH;
	right_inches = (float)R_ticks/RIGHT_CLICKS_PER_INCH;

	//calculate distance the total robot has travled
	inches = (left_inches + right_inches) / 2.0;

	//change the angle of the robot
	thetaOdo += (left_inches - right_inches) / WHEEL_BASE;

	//Keeps the theta value within 0 and 2*PI radians
	if(thetaOdo >= 2*PI)
	{
		thetaOdo = thetaOdo - 2 * PI;
	}

	else if (thetaOdo < 0)
	{
		thetaOdo =  thetaOdo + 2 * PI;
	}

	y1 = yOdo;
	x1 = xOdo;
	/* now calculate and accumulate our position in inches */
	yOdo += inches * sin(thetaOdo);
	xOdo += inches * cos(thetaOdo);
}
/*-----------------------------------------------------------------------------------------*/

/*--------------------------------------Accelerometer--------------------------------------*/
//Variables
float thetaAcc = PI/2;                    /* bot heading */
float xAcc=0;                    /* bot X position in inches */
float yAcc=0;                    /* bot Y position in inches */
float initalLeftAccelVal = 0;
float initialRightAccelVal = 0;
float calibrateAccelLeft = 0;
float calibrateAccelRight = 0;

//Accelerometer task control
void accelerometerPosition()
{
	float instaAccelRight = SensorValue[accelRight];
	float instaAccelLeft = SensorValue[accelLeft];
	float instaVelocityRight;
	float instaVelocityLeft;
	wait1Msec(50);//Allow for new values to come in before updating
}
/*-----------------------------------------------------------------------------------------*/

/*--------------------------------------Kalman Filter--------------------------------------*/

//Variables
float x_pos = 0;
float y_pos = 0;
float theta = PI/2;

//Supporting functions

void resetValue()
{
	//Odometry Values
	xOdo = x_pos;
	yOdo = y_pos;
	thetaOdo = theta;

	//Acceleromter Values
	xAcc = x_pos;
	yAcc = y_pos;
	thetaAcc = theta;
}

task kalmanFilter()
{
	while(true)
	{
		odometry();
		accelerometerPosition();
		/*
			In here I will take the values from the two tasks to come up with one final x,y value
		*/

		wait1Msec(60); //Allow values to repopulate
	}
}
/*-----------------------------------------------------------------------------------------*/

void setDefault()
{
	//Clear all motor encoders
	nMotorEncoder[backLeft] = 0;
	nMotorEncoder[backRight] = 0;
	nMotorEncoder[frontLeft] = 0;
	nMotorEncoder[frontRight] = 0;

	//Reselt Odometry values
	xOdo = 0;
	yOdo = 0;
	thetaOdo = PI/2;

	//Reset Acceleromer values
	xAcc = 0;
	yAcc = 0;
	thetaAcc = PI/2;
	initalLeftAccelVal = SensorValue[accelLeft];
	initialRightAccelVal = SensorValue[accelRight];
	calibrateAccelLeft = (SensorValue[accelLeftZ] - intialLeftAccelVal) / 9.801; //Creates conversion factor from vex acceleromter values to m/s^2
	calibrateAccelRight = (SensorValue[accelRightZ] - intialRightAccelVal) / 9.801; //Creates conversion factor from vex acceleromter values to m/s^2
	//Reset all Kalman values
	x_pos = 0;
	y_pos = 0;
	theta = PI/2;
}

task main()
{
	setDefault();
	startTask(kalmanFilter);
	while(true)
	{
		motor[backLeft] = vexRT[Ch3];
		motor[backRight] = vexRT[Ch2];
	}

}
