#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    rightPot,       sensorPotentiometer)
#pragma config(Sensor, in2,    leftPot,        sensorPotentiometer)
#pragma config(Sensor, in3,    autoControl,    sensorNone)
#pragma config(Sensor, in4,    accelRight,     sensorAccelerometer)
#pragma config(Sensor, in5,    accelLeft,      sensorAccelerometer)
#pragma config(Sensor, dgtl1,  autoSensor,     sensorTouch)
#pragma config(Sensor, dgtl2,  bottomLimit,    sensorNone)
#pragma config(Sensor, dgtl3,  autoSensor,     sensorNone)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           rightPincer,   tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           bottomRight,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           topLeft,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           frontRight,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           frontLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           backRight,     tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port7,           backLeft,      tmotorVex393_MC29, openLoop, encoderPort, I2C_2)
#pragma config(Motor,  port8,           bottomLeft,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           topRight,      tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_3)
#pragma config(Motor,  port10,          leftPincer,    tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*--------------------------------General Variables ------------------------------*/
float WHEEL_BASE = 30;
float LEFT_CLICKS_PER_INCH = 27;
float RIGHT_CLICKS_PER_INCH = 27;
float traveled = 0;								//distanced traveled from set point

/*--------------------------------------------------------------------------------*/

/*--------------------------------Odometry ---------------------------------------*/
//Variables
float thetaOdo = PI/2;                    /* bot heading */
float xOdo=0;                    /* bot X position in inches */
float yOdo=0;                    /* bot Y position in inches */

//Odomery
task odometry()
{
	nMotorEncoder[backRight] = 0;
	nMotorEncoder[backLeft] = 0;
	int lsamp = 0;
	int rsamp = 0;
	int L_ticks = 0;
	int R_ticks = 0;
	int last_left = 0;
	int last_right = 0;
	float x1,y1;
	float left_inches, right_inches, inches;
	while (true)
	{
		lsamp = nMotorEncoder[backRight];
		rsamp = nMotorEncoder[backLeft];

		//Change in encoder values
		L_ticks = lsamp - last_left;
		R_ticks = rsamp - last_right;

		//Update past encodervalues for next pass
		last_left = lsamp;
		last_right = rsamp;

		//Calculate the distance each wheel has travled
		left_inches = (float)L_ticks/LEFT_CLICKS_PER_INCH;
		right_inches = (float)R_ticks/RIGHT_CLICKS_PER_INCH;

		//calculate distance the total robot has travled
		inches = (left_inches + right_inches) / 2.0;

		//change the angle of the robot
		thetaOdo += (left_inches - right_inches) / WHEEL_BASE;

		//Keeps the theta value within 0 and 2*PI radians
		if(thetaOdo >= 2*PI)
		{
			thetaOdo = thetaOdo - 2 * PI;
		}

		else if (thetaOdo < 0)
		{
			thetaOdo =  thetaOdo + 2 * PI;
		}

		y1 = yOdo;
		x1 = xOdo;
		/* now calculate and accumulate our position in inches */
		yOdo += inches * sin(thetaOdo);
		xOdo += inches * cos(thetaOdo);
		wait1Msec(50);//Allow for new values to come in before updating
	}
}
/*-----------------------------------------------------------------------------------------*/

/*--------------------------------------Accelerometer--------------------------------------*/
//Variables
float thetaAcc = PI/2;                    /* bot heading */
float xAcc=0;                    /* bot X position in inches */
float yAcc=0;                    /* bot Y position in inches */

//Accelerometer task control
task accelerometerPosition()
{
	float instaAccelRight = SensorValue[accelRight];
	float instaAccelLeft = SensorValue[accelLeft];
	float instaVelocityRight;
	float instaVelocityLeft;
	wait1Msec(50);//Allow for new values to come in before updating
}
/*-----------------------------------------------------------------------------------------*/

/*--------------------------------------Kalman Filter--------------------------------------*/
/*-----------------------------------------------------------------------------------------*/
task main()
{
	startTask(odometry);
	startTask(accelerometerPosition);


}
