#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    rightPot,       sensorPotentiometer)
#pragma config(Sensor, in2,    leftPot,        sensorPotentiometer)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           leftDriveFront, tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           rightDriveFront, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           leftLiftBottom, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           leftLiftTop,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           rightPincer,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           leftPincer,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           rightLiftBottom, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           rightLiftTop,  tmotorVex393_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port9,           rightDriveBack, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          leftDriveBack, tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
	12/23/2016
	Collin Bolles
	Tank Drive control
	arm motion
	pincher motion open and close control automatic and manual
*/

int lockArmPosition = nMotorEncoder[rightLiftTop];
int additionPower = 0;

void moveDump(int speed)
{
	motor[rightLiftTop] = speed;
	motor[rightLiftBottom] = speed;
	motor[leftLiftTop] = speed;
	motor[leftLiftBottom] = speed;
	lockArmPosition = nMotorEncoder[rightLiftTop];
}

void lockArm()
{
	if(lockArmPosition > nMotorEncoder[rightLiftTop]+3)
	{
		additionPower += 2; //Increment by 2
	}
	moveDump(additionPower); //Zero if locked it on its own
}

void controlDump()
{
	int speed = 80;
	if(vexRT[Btn6U])
	{
		moveDump(speed);
		additionPower = 0;
	}
	else if(vexRT[Btn6D])
	{
		moveDump(-speed);
		additionPower = 0;
	}
	else
	{
		lockArm();
		//moveDump(0);
	}
}

void driveControl()
{
	motor[rightDriveBack] = vexRT[Ch2];
	motor[rightDriveFront] = vexRT[Ch2];

	motor[leftDriveBack] = vexRT[Ch3];
	motor[leftDriveFront] = vexRT[Ch3];
}

void manualMovePincer()
{
	int pincerSpeed = 50;
	//Left Pincer
	if(vexRT[Btn7L])
	{
		motor[leftPincer] = pincerSpeed;
	}
	else if(vexRT[Btn7R])
	{
		motor[leftPincer] = -pincerSpeed;
	}
	else
	{
		motor[leftPincer] = 0;
	}

	//Right pincer
	if(vexRT[Btn8R])
	{
		motor[rightPincer] = pincerSpeed;
	}
	else if(vexRT[Btn8L])
	{
		motor[rightPincer] = -pincerSpeed;
	}
	else
	{
		motor[rightPincer] = 0;
	}
}

void automaticMovePincer()
{
	int positionCloseRight = 3940;
	int positionCloseLeft = 3400;

	int positionOpenRight = 2065;
	int positionOpenLeft = 1775;

	int positionFarRight = 0;
	int positionFarLeft = 0;

	int tolorance = 120;

	int pincerSpeed = 70;

	//Close Position
if(vexRT[Btn5D])
	{
		//right pincher
		if(SensorValue[rightPot] > positionOpenRight + tolorance)
		{
			motor[rightPincer] = pincerSpeed;
		}
		else if(SensorValue[rightPot] < positionOpenRight-tolorance)
		{
			motor[rightPincer] = -pincerSpeed;
		}
		else
		{
			motor[rightPincer] = 0;
		}

		//left pincher
		if(SensorValue[leftPot] > positionOpenLeft+tolorance)
		{
			motor[leftPincer] = pincerSpeed;
		}
		else if(SensorValue[leftPot] < positionOpenLeft-tolorance)
		{
			motor[leftPincer] = -pincerSpeed;
		}
		else
		{
			motor[leftPincer] = 0;
		}
	}

	//Close control
	else if(vexRT[Btn5U])
	{
		//right pincer
		if(SensorValue[rightPot] > positionCloseRight+tolorance)
		{
			motor[rightPincer] = pincerSpeed;
		}
		else if(SensorValue[rightPot] < positionCloseRight-tolorance)
		{
			motor[rightPincer] = -pincerSpeed;
		}
		else
		{
			motor[rightPincer] = 0;
		}

		//left pincher
		if(SensorValue[leftPot] > positionCloseLeft+tolorance)
		{
			motor[leftPincer] = pincerSpeed;
		}
		else if(SensorValue[leftPot] < positionCloseLeft-tolorance)
		{
			motor[leftPincer] = -pincerSpeed;
		}
		else
		{
			motor[leftPincer] = 0;
		}
	}
	else if(vexRT[Btn8D])//Getting into tight corners
	{
				//right pincer
		if(SensorValue[rightPot] > positionFarRight+tolorance)
		{
			motor[rightPincer] = pincerSpeed;
		}
		else if(SensorValue[rightPot] < positionFarRight-tolorance)
		{
			motor[rightPincer] = -pincerSpeed;
		}
		else
		{
			motor[rightPincer] = 0;
		}

		//left pincher
		if(SensorValue[leftPot] > positionFarLeft+tolorance)
		{
			motor[leftPincer] = pincerSpeed;
		}
		else if(SensorValue[leftPot] < positionFarLeft-tolorance)
		{
			motor[leftPincer] = -pincerSpeed;
		}
		else
		{
			motor[leftPincer] = 0;
		}
	}
}

task main()
{
	nMotorEncoder[rightLiftTop] = 0;
	lockArmPosition = nMotorEncoder[rightLiftTop];
	while(true)
	{
		driveControl();
		controlDump();
		manualMovePincer();
		automaticMovePincer();
	}
}
