#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  topLimit,       sensorTouch)
#pragma config(Sensor, dgtl2,  bottomLimit,    sensorTouch)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port2,           bottomRight,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           topLeft,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           FR,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           LE,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           RI,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           BK,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           bottomLeft,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           topRight,      tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define C1LX vexRT[Ch4]
#define C1LY vexRT[Ch3]
#define C1RX vexRT[Ch1]

int lockArmPosition = nMotorEncoder[topLeft];
int additionPower;


void moveShooter(int speed)
{
	motor[bottomLeft] = speed;
	motor[bottomRight] = speed;
	motor[topLeft] = speed;
	motor[topRight] = speed;
}

void lockArm()
{
	if(lockArmPosition <= nMotorEncoder[topLeft])
	{
		moveShooter(5 + additionPower); //If it counties to slip, keep additing power
		additionPower += 2; //Increment by 2
	}
	else
	{
		moveShooter(0); //Dont move if fine
	}
}

void driveControl()
{
	motor[FR] = C1LX + C1RX;
	motor[LE] =  -C1LY + C1RX;
	motor[RI] =  C1LY + C1RX;
	motor[BK] = -C1LX + C1RX;
	lockArmPosition = nMotorEncoder[topLeft];
}

//Basic up down moving, when not suppose to move, adds power to make sure it wont move
void dumpControl()
{
	if(!SensorValue[bottomLimit]) //While not touching botto sensor
	{
		if(vexRT[Btn6U])
		{
			additionPower = 0;
			moveShooter(75);
		}
		else if(vexRT[Btn6D])
		{
			additionPower = 0;
			moveShooter(-75);
		}
		else if(vexRT[Btn5U])
		{
			additionPower = 0;
			moveShooter(30);
		}
		else if(vexRT[Btn5D])
		{
			additionPower = 0;
			moveShooter(-30);
		}
		else
		{
			lockArm();
		}
	}
	else //If bottom sensor pressed
	{
		moveShooter(20);
	}
}

task main()
{
	while(true)
	{
		driveControl();
		dumpControl();
		wait10Msec(2); //Motors can only be updated every 20ms
	}
}
