#pragma config(Sensor, dgtl1,  topLimit,       sensorTouch)
#pragma config(Sensor, dgtl2,  bottomLimit,    sensorTouch)
#pragma config(Motor,  port2,           bottomRight,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           topLeft,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           FL,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           FR,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           BR,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           BL,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           bottomLeft,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           topRight,      tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define C1LX vexRT[Ch4]
#define C1LY vexRT[Ch3]
#define C1RX vexRT[Ch1]


task main()
{
	while(true)
	{
		//Base drive train control
		motor[FL] = -C1LY - C1LX - C1RX;
		motor[FR] =  C1LY - C1LX - C1RX;
		motor[BR] =  C1LY + C1LX - C1RX;
		motor[BL] = -C1LY + C1LX - C1RX;

		//Lift control
		if(vexRT[Btn6U] && !SensorValue[topLimit])
		{
			motor[bottomLeft] = 75;
			motor[bottomRight] = 75;
			motor[topLeft] = 75;
			motor[topRight] = 75;
		}
		else if(vexRT[Btn6D] && !SensorValue[bottomLimit])
		{
			motor[bottomLeft] = -75;
			motor[bottomRight] = -75;
			motor[topLeft] = -75;
			motor[topRight] = -75;
		}
		else
		{
			motor[bottomLeft] = 0;
			motor[bottomRight] = 0;
			motor[topLeft] = 0;
			motor[topRight] = 0;
		}
	}


}
