#pragma config(Sensor, dgtl1,  topLimit,       sensorTouch)
#pragma config(Sensor, dgtl2,  bottomLimit,    sensorTouch)
#pragma config(Motor,  port2,           bottomRight,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           topLeft,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           FL,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           FR,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           BR,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           BL,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           bottomLeft,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           topRight,      tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
	{
		if(vexRT[Btn7D])
		{
			motor[bottomLeft] = 75;
		}
		else if(vexRT[Btn7R])
		{
			motor[topLeft] = 75;
		}
		else if(vexRT[Btn8D])
		{
			motor[bottomRight] = 75;
		}
		else if(vexRT[Btn8U])
		{
			motor[topRight] = 75;
		}
		else
		{
			motor[bottomLeft] = 0;
			motor[bottomRight] = 0;
			motor[topLeft] = 0;
			motor[topRight] = 0;
		}
	}
}
