#pragma config(Sensor, dgtl1,  armEncoder,     sensorQuadEncoder)
#pragma config(Motor,  port1,           leftArm2,      tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           backLeft,      tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           frontLeft,     tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           leftArmWired,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           leftArm1,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           rightArmWired, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           rightArm1,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           backRight,     tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           frontRight,    tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          rightArm2,     tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)

#pragma competitionControl(Competition)

#include "Vex_Competition_Includes.c"

int lockArmPosition = 0;
int additionalPower = 0;

void pre_auton()
{
	bStopTasksBetweenModes = true;
}


task baseDrive()
{
	while(true){
	motor[backLeft] = -vexRT[Ch2]/2;
	motor[backRight] = -vexRT[Ch3]/2;

	motor[frontLeft] = -vexRT[Ch2]/2;
	motor[frontRight] = -vexRT[Ch3]/2;
}
}



void moveArm(int speed)
{
	motor[rightArm1] = speed;
	motor[rightArm2] = speed;
	motor[rightArmWired] = speed;
	motor[leftArm1] = speed;
	motor[leftArm2] = speed;
	motor[leftArmWired] = speed;
}

void lockArm()
{
	if(lockArmPosition > SensorValue[armEncoder])
	{
		additionalPower += 2;
	}
	moveArm(additionalPower);
}

task controlArm()
{
	while (true){
	int maxSpeed = 90;
	if(vexRT[Btn6U])
	{
		moveArm(maxSpeed);
		lockArmPosition = SensorValue[armEncoder];
		additionalPower = 0;
	}
	else if(vexRT[Btn6D])
	{
		moveArm(-maxSpeed);
		lockArmPosition = SensorValue[armEncoder];
		additionalPower = 0;
	}
	else if(vexRT[Btn8L])
	{
		lockArm();
	}
	else
	{
		moveArm(0);
	}
}
}

float WHEEL_BASE = 30;
float LEFT_CLICKS_PER_INCH = 27;
float RIGHT_CLICKS_PER_INCH = 27;
float theta = PI/2;                    /* bot heading */
float X_pos=0;                    /* bot X position in inches */
float Y_pos=0;                    /* bot Y position in inches */
float traveled = 0;								//distanced traveled from set point
/*----------------------------------------------------------------------------------*/

/*----------------------------------------------------------------------------------*/

/*----------------------------Arm movement functions--------------------------------*/

int degreesToTicks(int degrees)
{
	return (int)(degrees / 0.078);//0079 degrees per tick
}

void moveArmDegree(float degrees, int speed)
{
	if(SensorValue[armEncoder] < degrees)
	{
		while(SensorValue[armEncoder] < degrees)
		{
			moveArm(speed);
		}
	}
	else
	{
		while(SensorValue[armEncoder] > degrees)
		{
			moveArm(-speed);
		}
	}
	moveArm(0);
}
/*----------------------------------------------------------------------------------*/

/*---------------------------Drive base functions-----------------------------------*/
void driveForward(int speed)
{
	motor[backRight] = -speed;
	motor[backLeft] = -speed;

	motor[frontRight] = -speed;
	motor[frontLeft] = -speed;
}

void driveBackward(int speed)
{
	motor[backRight] = speed;
	motor[backLeft] = speed;

	motor[frontRight] = speed;
	motor[frontLeft] = speed;
}



void driveLeftward(int speed)
{
	motor[frontRight] = speed;
	motor[frontLeft] = speed;

	motor[backRight] = -speed;
	motor[backLeft] = -speed;
}

void driveRightward(int speed)
{
	motor[frontRight] = -speed;
	motor[frontLeft] = -speed;

	motor[backRight] = speed;
	motor[backLeft] = speed;
}

void turnRight(int speed)
{
	motor[frontRight] = -speed;
	motor[frontLeft] = speed;

	motor[backRight] = -speed;
	motor[backLeft] = speed;
}

void turnLeft(int speed)
{
	motor[frontRight] = speed;
	motor[frontLeft] = -speed;

	motor[backRight] = speed;
	motor[backLeft] = -speed;
}

void stopBase()
{
	motor[frontRight] = 0;
	motor[frontLeft] = 0;

	motor[backRight] = 0;
	motor[backLeft] = 0;
}

void driveForward(int targetDistance, int speed)
{
	float startPositionX = X_pos;
	float startPositionY = Y_pos;
	float distance = 0;
	while(distance < targetDistance)
	{
		driveForward(speed);
		distance = sqrt(pow(X_pos - startPositionX, 2) + pow(Y_pos - startPositionY, 2));
		wait10Msec(2);
	}
	stopBase();
}

void driveBackward(int targetDistance, int speed)
{
	float startPositionX = X_pos;
	float startPositionY = Y_pos;
	float distance = 0;
	while(distance < targetDistance)
	{
		driveBackward(speed);
		distance = sqrt(pow(X_pos - startPositionX, 2) + pow(Y_pos - startPositionY, 2));
		wait10Msec(2);
	}
	stopBase();
}

bool inRange(float value, float target, float tolerance)
{
	return abs(value-target) <= tolerance;
}

void turnRight(float targetTheta, int speed)
{
	while(!inRange(theta, targetTheta, 0.09))
	{
		turnRight(speed);
	}
	stopBase();
}

void turnLeft(float targetTheta, int speed)
{
	while(!inRange(theta, targetTheta, 0.09))
	{
		turnLeft(speed);
	}
	stopBase();
}

void goToPoint(float x, float y, int speed)
{
	float xDistance = x - X_pos+.01;
	float yDistance = y - Y_pos;
	float angleToPoint = atan2(yDistance,xDistance);
	float distanceToPoint = sqrt(pow(X_pos - x, 2) + pow(Y_pos - y, 2));
	if(angleToPoint < 0)
	{
		angleToPoint += 2*PI;
	}
	writeDebugStreamLine("%f:",angleToPoint);
	if(theta - angleToPoint > .09)
	{
		turnRight(angleToPoint, speed);
	}
	else if(theta - angleToPoint < -0.09)
	{
		turnLeft(angleToPoint, speed);
	}
	driveForward(distanceToPoint, speed);
}
/*----------------------------------------------------------------------------------*/

task odometry()
{
	nMotorEncoder[backRight] = 0;
	nMotorEncoder[backLeft] = 0;
	int lsamp = 0;
	int rsamp = 0;
	int L_ticks = 0;
	int R_ticks = 0;
	int last_left = 0;
	int last_right = 0;
	float x1,y1;
	float left_inches, right_inches, inches;
	while (true)
	{
		lsamp = nMotorEncoder[backRight];
		rsamp = nMotorEncoder[backLeft];

		//Change in encoder values
		L_ticks = lsamp - last_left;
		R_ticks = rsamp - last_right;

		//Update past encodervalues for next pass
		last_left = lsamp;
		last_right = rsamp;

		//Calculate the distance each wheel has travled
		left_inches = (float)L_ticks/LEFT_CLICKS_PER_INCH;
		right_inches = (float)R_ticks/RIGHT_CLICKS_PER_INCH;

		//calculate distance the total robot has travled
		inches = (left_inches + right_inches) / 2.0;

		//change the angle of the robot
		theta += (left_inches - right_inches) / WHEEL_BASE;

		//Keeps the theta value within 0 and 2*PI radians
		if(theta >= 2*PI)
		{
			theta = theta - 2 * PI;
		}

		else if (theta < 0)
		{
			theta =  theta + 2 * PI;
		}

		y1 = Y_pos;
		x1 = X_pos;
		/* now calculate and accumulate our position in inches */
		Y_pos += inches * sin(theta);
		X_pos += inches * cos(theta);

		traveled += sqrt(pow(X_pos-x1,2) + pow(Y_pos-y1,2));//distance formula, used like a resetable sensor
		wait1Msec(50);//Allow for new values to come in before updating
	}
}

void setToDefault()
{
	SensorValue[armEncoder] = 0;
	nMotorEncoder[backLeft] = 0;
	nMotorEncoder[backRight] = 0;
	X_pos = 0;
	Y_pos = 0;
	theta = 3*PI/2;
	additionalPower = 0;
}


task autonomous()
{
	setToDefault();
	startTask(odometry);
	driveForward(20, 75);
	//moveArmDegree(200, 75);
	driveForward(5, 75);
	driveBackward(15, 75);
	driveForward(15, 75);
}

task usercontrol()
{
	//while (true)
	//{
		startTask(baseDrive);
		startTask(controlArm);
	//}
}
